deployment:
  tasks:
    - export DEPLOYPATH=/home/spectmdh/public_html/
    # - export DEPLOYPATH=/home/spectmdh/sbs.services
    - /bin/cp index.html $DEPLOYPATH
    - /bin/cp -R assets $DEPLOYPATH
    - /bin/cp -R images $DEPLOYPATH
    - /bin/cp -R app $DEPLOYPATH
    - /bin/cp .htaccess $DEPLOYPATH
    - /bin/cp manifest.json $DEPLOYPATH
    - export DEPLOYPATH=/home/spectmdh/sbs.services/
    - /bin/cp index.html $DEPLOYPATH
    - /bin/cp -R assets $DEPLOYPATH
    - /bin/cp -R images $DEPLOYPATH
    - /bin/cp -R app $DEPLOYPATH
    - /bin/cp .htaccess $DEPLOYPATH
    - /bin/cp manifest.json $DEPLOYPATH
