deployment:
  tasks:
    - export DEPLOYPATH=/home/spectmdh/public_html/
    - export DEPLOYPATH=/home/spectmdh/sbs.services/
    - /bin/cp index.html $DEPLOYPATH
    - /bin/cp -R assets $DEPLOYPATH
    - /bin/cp -R images $DEPLOYPATH
    - /bin/cp -R app $DEPLOYPATH
    tasks:
      - export DEPLOYPATH=/home/spectmdh/public_html/
      - /bin/cp index.html $DEPLOYPATH
      - /bin/cp -R assets $DEPLOYPATH
      - /bin/cp -R images $DEPLOYPATH
      - /bin/cp -R app $DEPLOYPATH
